// <auto-generated />
using System;
using HomeLibServices.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeLib.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20200903091333_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeLibServices.Models.Author", b =>
                {
                    b.Property<long>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("FullName");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("");

                    b.HasKey("AuthorId");

                    b.HasAlternateKey("FirstName", "MiddleName", "LastName");

                    b.HasIndex("FullName");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("HomeLibServices.Models.Authorship", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AuthorId")
                        .HasColumnName("Id_Author");

                    b.Property<long>("BookId")
                        .HasColumnName("Id_Book");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId");

                    b.ToTable("Authorship");
                });

            modelBuilder.Entity("HomeLibServices.Models.Book", b =>
                {
                    b.Property<long>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Annotation");

                    b.Property<string>("Isbn");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<string>("Year");

                    b.HasKey("BookId");

                    b.HasIndex("Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("HomeLibServices.Models.Authorship", b =>
                {
                    b.HasOne("HomeLibServices.Models.Author", "Author")
                        .WithMany("Authorships")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HomeLibServices.Models.Book", "Book")
                        .WithMany("Authorships")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeLibServices.Models.Book", b =>
                {
                    b.OwnsOne("HomeLibServices.Models.LocalPath", "Path", b1 =>
                        {
                            b1.Property<long?>("BookId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("ArchiveName");

                            b1.Property<string>("FbName");

                            b1.HasIndex("ArchiveName");

                            b1.HasIndex("FbName");

                            b1.ToTable("Books");

                            b1.HasOne("HomeLibServices.Models.Book")
                                .WithOne("Path")
                                .HasForeignKey("HomeLibServices.Models.LocalPath", "BookId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
