// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScannerService.Models;

namespace ScannerService.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20190606150141_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScannerService.Models.Authtor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Authtors");
                });

            modelBuilder.Entity("ScannerService.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthtorFirstName");

                    b.Property<string>("AuthtorLastName");

                    b.Property<string>("AuthtorMiddleName");

                    b.Property<string>("PathArchive");

                    b.Property<string>("PathBook");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.HasIndex("AuthtorFirstName", "AuthtorMiddleName", "AuthtorLastName");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ScannerService.Models.Book", b =>
                {
                    b.HasOne("ScannerService.Models.Authtor", "Authtor")
                        .WithMany("Books")
                        .HasForeignKey("AuthtorFirstName", "AuthtorMiddleName", "AuthtorLastName")
                        .HasPrincipalKey("FirstName", "MiddleName", "LastName");
                });
#pragma warning restore 612, 618
        }
    }
}
